### ISSUE TITLE
Patchwork Armor Issues

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#10] opened 2016-03-12 19:32 UTC
Its a pretty small one (okay, maybe 2 or three), but it popped up recently...

If you make a Mech with patchwork armor, and then click on the "New Mech" button, the Patchwork armor GUI remains, instead of disappearing. This seems to be an issue with just with "New Mech" as loading a new design removes the GUI, as does selecting a new armor type. So just a "New Mech" button issue as far as I can tell.

2nd issue..if you select "Quad" and then "Patchwork Armor" the Patchwork Armor GUI correctly shows the Front Left Leg and Front Right Leg of the quad. However, if you select "Patchwork Armor" and then "Quad" the Patchwork armor GUI doesn't update, and you still have it labeled as Right Arm and Left Arm.

Actually, I just checked and it doesn't seem to update the GUI If you have Patchwork Armor selected and you change between Quad and Biped. So if you have a quad, patchwork armor, and the patchwork armor GUI shows the front right left and front left leg, and then you change the Mech to a Biped, the Patchwork Armor still has the Front Leg labels.

And it does seem to be just a label issue. Even though I'm testing on a biped, and the Arms are labeled as Front Left Leg, it still calculates correctly when you add arm armor.

3rd issue seems to be part of Skyhigh's attempt to add Tripods. Even on Bipeds and Quads, when you select Patchwork Armor, a dropdown box labeled "CL" (for Center Leg) appears. Obviously this should only appear when you select Tripod. Also, instead of listing armor types in the dropdown box, it lists "Item 1" "Item 2" "Item 3" "Item 4". Obviously that's incorrect, but is most likely due to tripods being half coded, rather than an error.

Sorry, this one was longer than expected, maybe I should've broken it up...

**Comment by WEKarnesky** [comment] 2019-07-13 01:35
Bug report from Discord User Xotl

> Confirmed still there.  You don't have to choose any of the Patchwork Armour subtypes: just selecting the base Patchwork Armour option is enough.  You also don't need to be looking at the Armour tab when selecting "New Mech" to create the issue: I selected New Mech when looking at the Basic Setup tab and it happened.  The new mech reads as Tourney Legal / Age of War etc as normal, but the Patchwork dropdown subtype menus are there despite Standard Armour being selected as you'd expect for a default New Mech.
> 
> PW Armour Error
> https://cdn.discordapp.com/attachments/598176054766600234/599372310021013514/Patchwork_Error.PNG
> 
> Also confirmed that if you have Patchwork selected and toggle from Biped to Quad, the Patchwork subtype menus don't switch from arms to legs.
> The reverse is also true: if you make a Quad, add Patchwork, then switch to Biped, the subtype menus don't switch to two arms and two legs: they stay at four legs.

**Comment by Algebro7** [comment] 2019-07-13 19:30
This issue was mistakenly closed because of the commit message pertaining to SSWLib. Reopening

**Comment by Algebro7** [comment] 2019-07-13 20:24
Anyone care to test the quad/biped patchwork issues with this build? It should resolve issues 1 and 2 but it would be good to know I didn't break anything else.

[SSW_0.7-Experimental-6.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3389205/SSW_0.7-Experimental-6.zip)

**Comment by WEKarnesky** [comment] 2019-07-13 21:07
I have confirmed that I can not replicate any of the stated issues with the experimental

**Comment by Algebro7** [comment] 2019-07-13 23:36
Closing this with eaa8f83, but I updated another issue with a reminder to check out the UI bug with the center leg once we get around to implementing tripod mechs

**Closed by Algebro7** 2019-07-13 23:36 UTC
Labels: bug
