### ISSUE TITLE
Skunkwerks 0.7.4.1 not printing Fluffimages of some Mechs from Forcelist

### ISSUE THREAD

**Issue by Andai82** [Solaris-Skunk-Werks/solarisskunkwerks#195] opened 2020-10-09 10:26 UTC
SSW 07.4.1 is having a Forcelist issue, when adding multiple mechs, he is not printing the mechimage on the sheet. When doing a manual single mech print it is still there and being printed.
 - Showing the empty Fluffpicture of the Mad Cat A in ForceList and printing preview
![02](https://user-images.githubusercontent.com/56923846/95572444-41932a80-0a2a-11eb-9918-fa5b27a3fd3c.PNG)
- Showing the same Forcelist for a Firefly and this time image is previewed and printed
![03](https://user-images.githubusercontent.com/56923846/95572513-596aae80-0a2a-11eb-8c0f-eaf929cdf64d.PNG)
- The Forcelist units
![04](https://user-images.githubusercontent.com/56923846/95572558-68516100-0a2a-11eb-99eb-f222e5b18c67.PNG)
- Mad Cat opened in SSW and showing image
![05](https://user-images.githubusercontent.com/56923846/95572572-6e474200-0a2a-11eb-9bc3-7206091b46e0.PNG)
- Showing mad cat printed directly (without forcelist) and image also printed
![06](https://user-images.githubusercontent.com/56923846/95572593-78694080-0a2a-11eb-89f1-69274bf974e4.PNG)

Prints were done with PDF24 Creater but problem already occurs on the forcelist before printing!

**Comment by WEKarnesky** [comment] 2020-10-13 16:14
Can you tell me if you still have this problem in this Snapshot?  I am not able to reproduce it.


[SSW_0.7.5.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/5372649/SSW_0.7.5.zip)

**Comment by Andai82** [comment] 2020-10-14 08:31
Hello,

 

yes, it still exists. It was not in the SSW 0.7.3 versions.

Just add some mechs to the Force List and print from there. Even in the preview you will see some images missing. maybe the type of image is important? Because he shows my jpeg images with the force unit list, but not the .png ones!


He adds my fluff images while i single open a mech or print only this opened mech directly, but while doing that for multiple units in the force list, some are missing their mech pictures.

 

Kind regards,

Andreas

 
 

Gesendet: Dienstag, 13. Oktober 2020 um 18:15 Uhr
Von: "William E. Karnesky" <notifications@github.com>
An: "Solaris-Skunk-Werks/solarisskunkwerks" <solarisskunkwerks@noreply.github.com>
Cc: "Andai82" <nicksgizmo@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Solaris-Skunk-Werks/solarisskunkwerks] Skunkwerks 0.7.4.1 not printing Fluffimages of some Mechs from Forcelist (#195)


 

Can you tell me if you still have this problem in this Snapshot? I am not able to reproduce it.

SSW_0.7.5.zip

**Comment by WEKarnesky** [comment] 2020-10-14 13:22
I think I only tested with jpgs, I'll test with PNG and see what I can find thank you for that information.

**Comment by Andai82** [comment] 2020-12-05 12:42
Hello,

tested yesterday with the new stable 0.7.5..s.eems it got worth, now he isn´t even taking jpegs...so Force printing with Fluff Images seems to be totally broken.

He recognizes the fluff pictures for a single machine and prints it, but as soon as you try to print multiple thorugh force list, no fluff pictures included.

**Comment by WEKarnesky** [comment] 2020-12-05 14:39
@Maelwys Can you reproduce this?

**Comment by gblouin** [comment] 2021-03-09 03:35
I think this may be fixed with the image path handling I just added.

**Closed** 2023-01-29 00:27 UTC
Labels: bug, review
