### ISSUE TITLE
BFB can't print recordsheets.

### ISSUE THREAD

**Issue by johndavismit** [Solaris-Skunk-Werks/solarisskunkwerks#109] opened 2020-01-04 06:18 UTC
Version affected: SSW_0.7.3.20200101

Repro steps:
1. Open BFB
2. Add 2 Mechs to Primary Force Listing
3. go to File>Print>Print Options
4. Ensure Unit Record sheets is checked.
5. Click Print
6. Observe that the application soft locks. 

Expected behavior: Print prompt appears
Actual behavior: App softlocks.

**Comment by WEKarnesky** [comment] 2020-01-04 10:33
I think this is the same as #54.  Which I thought, but I am not sure, that we resolved.  If it is the same issue, try these steps:

1. run ssw
2. load a mech and point it to the master list when prompted
3. then exit and run bfb and try to print

You may need to go into HKEY_CURRENT_USER\Software\JavaSoft\Prefs\com\sswsuite and delete everything there first.

@Algebro7 you were the one who put more work into this, are you able to provide input?

**Comment by WEKarnesky** [comment] 2020-01-11 03:49
Have confirmed that this is a Duplicate of #54

**Closed by WEKarnesky** 2020-01-11 03:49 UTC
Labels: bug, duplicate
