### ISSUE TITLE
mass bulk converter of SSW files directories into MTF files directories

### ISSUE THREAD

**Issue by Mekslayer** [Solaris-Skunk-Werks/solarisskunkwerks#217] opened 2020-12-02 17:39 UTC
**Is your feature request related to a problem? Please describe.**
Yes, I godam hate doing this one file at a time

**Describe the solution you'd like**
Can I make a feature request? I have always found the mass bulk converter in SSW that converts whole directories of HMP files to SSW files. Can someone please make a mass bulk converter of SSW files directories into MTF files directories? 

**Describe alternatives you've considered**
see 1,  I godam hate doing this conversion from one SSW file to one MTF file one at a time.

**Additional context**
Nope

**Comment by WEKarnesky** [comment] 2020-12-17 19:46
This is a duplicate of #216.  I will be adding the details of the ticket to that one and closing this.

**Closed by WEKarnesky** 2020-12-17 19:46 UTC
