### ISSUE TITLE
Linux - Cannot load SSW files due to "no protocol" error

### ISSUE THREAD

**Issue by MGM175** [Solaris-Skunk-Werks/solarisskunkwerks#101] opened 2019-11-05 19:30 UTC
When attempting to load a SSW from files provided in the Master repo, I'm recieving this kind of error:

![Zrzut ekranu z 2019-11-05 20-26-14](https://user-images.githubusercontent.com/20325180/68239068-a2400900-000a-11ea-9ca7-633d884bfe67.png)

So far, it happened on the two different computers, one had OpenJDK v. 11, second - 14-ea+18 b. 773.

No other errors (even in terminal) were registered.

**Comment by WEKarnesky** [comment] 2019-11-05 20:00
I'm not using linux, but I know @Algebro7 is, so I'm assigning this to him to see if he can replicate it and narrow down the cause, if so.

**Comment by WEKarnesky** [comment] 2019-11-05 20:27
@MGM175,

 @Algebro7 can not replicate the issue right now, can you specify which build and version you are using (Nightly/stable, and version number), and/or if you are building it yourself?

**Comment by MGM175** [comment] 2019-11-06 21:48
Used builds:

- 0.7.3.20191031 Nightly;
- 0.7.3.20191024 Nightly.

Master list was taken from:
https://github.com/Solaris-Skunk-Werks/SSW-Master
directly cloned each time.

**Comment by mrpopogod** [comment] 2019-11-06 23:44
I was able to repro this on Centos7 with Open JDK 1.8.  java -jar SSW.jar loads the app fine, I went Open and pointed it at my SSW files that I pulled from the GitHub repo, then tried to load the Catapult K2 and got the same "no protocol" issue.

I think the problem is the spaces in the filename.  If you move the Adder (Puma).ssw file under Clan/Omni to just be Adder.ssw, refresh your cache, then Open an Adder variant it loads just fine.

**Comment by MGM175** [comment] 2019-11-07 19:33
@mrpopogod @Algebro7 @WEKarnesky What about implementing a native OS dialog screens, like MML did?

**Comment by WEKarnesky** [comment] 2019-11-07 19:39
> What about implementing a native OS dialog screens, like MML did?

SSW does use native loading dialogs for the file loading.  The select mech screen is similar in purpose to MM's select mech screen and uses a cached and searchable list of mechs in order to quickly find mechs.  This is not possible to do in a native dialog and neither MM or SSW uses a native window for these screens

  If you want to use the system default while waiting for @Algebro7 to be able to fix it, then you can use File => Load Mech (The Alt+L hotkey should also work) to use the system default without any search powers, the menus is pictured below.

![image](https://user-images.githubusercontent.com/8506084/68421444-1eddff00-0153-11ea-8bd8-923f17786371.png)

**Comment by Algebro7** [comment] 2019-11-27 17:31
Should be fixed by #102, please re-open if you still have this problem.

**Closed by Algebro7** 2019-11-27 17:31 UTC
Labels: bug, need info
