### ISSUE TITLE
Unable to load Omnimechs

### ISSUE THREAD

**Issue by BKDOffice** [Solaris-Skunk-Werks/solarisskunkwerks#44] opened 2019-09-13 05:28 UTC
I was previously able to open or load Omnimechs I had created in 0.7, but am now getting the following error when attempting to do so: "Could not add the new loadout because the name given matches an existing loadout."

I had previously been deleting the "SSW_TEMP_LOADOUT_001" variants as they were cluttering the file list, but I am not sure whether that has anything to do with it.

![Capture](https://user-images.githubusercontent.com/55269960/64839426-4cbc2280-d5ac-11e9-9a3b-6a8fc5374030.PNG)

**Comment by mrpopogod** [comment] 2019-09-20 21:47
SSW_TEMP_LOADOUT_001 seems to be the thing that's causing issues.  When you add a variant and then save it both adds your variant and the TEMP file to the list.  If you then try to load any of the variants it fails.  Deleting that variant from the ssw file manually fixes it.

**Comment by Algebro7** [comment] 2019-09-23 15:50
Can you provide some example .ssw files that are affected by this?

**Comment by mrpopogod** [comment] 2019-09-23 16:17
See attached.  I took the base Warhawk ssw and added an "S" variant to it (which I didn't bother adding any weapons to, so it's just the empty Omni shell).

[Warhawk (Masakari).zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3643079/Warhawk.Masakari.zip)

**Comment by Algebro7** [comment] 2019-09-23 16:19
Thanks--I think I've identified the issue...when saving omnimechs, SSW currently saves the SSW TEMP loadout, which is only meant as a placeholder when loading the mech. Will work on a fix.

**Comment by Algebro7** [comment] 2019-09-23 16:44
Can you test this build and see if the issue is fixed? 

[SSW_0.7-Experimental.zip](https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/files/3643190/SSW_0.7-Experimental.zip)

**Comment by WEKarnesky** [comment] 2019-09-23 21:56
Fixed in #47

**Closed by WEKarnesky** 2019-09-23 21:56 UTC
Labels: SSW, bug
