### ISSUE TITLE
no protocol when selecting mech in Linux Mint

### ISSUE THREAD

**Issue by TimothyHD** [Solaris-Skunk-Werks/solarisskunkwerks#143] opened 2020-06-01 16:23 UTC
**Describe the bug**
When trying to open a mech from a Select Mech screen I get an error saying no protocol [path to file]. I click ok and it returns me to SSW.  I can open files by selecting them from the file chooser.

**To Reproduce**

1. click "open mech" button
2. double click on selected mech on Select Mech screen

**Expected behavior**
I would expect that it loads the selected mech to SSW

**Screenshots**
![bug](https://user-images.githubusercontent.com/16869657/83429314-7eef0800-a3f9-11ea-9b61-c1d08da8f9bd.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1 Cinnamon 4.0.10
 - Browser Chromium
 - Version  73.0.3683.86

**Smartphone (please complete the following information):**

**Additional context**
To run SSW  I need to load from terminal  using sudo or i get :
![bug2](https://user-images.githubusercontent.com/16869657/83429767-29672b00-a3fa-11ea-905e-296c49258e24.png)

**Comment by WEKarnesky** [comment] 2020-06-01 20:29
Can you give more details?  What version of SSW are you using?  This sounds like a duplicate of #140, but we believe that was resolved a while ago (though not closed until recently)

**Comment by TimothyHD** [comment] 2020-06-01 22:18
Using version 0.7.320191024

**Comment by WEKarnesky** [comment] 2020-06-02 00:19
Please try to reproduce using the latest pre-release, version 0.7.3.202000413

https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/releases/tag/0.7.3.202000413

**Comment by TimothyHD** [comment] 2020-06-02 02:28
That worked. I was downloading from solarisskunkwerks.com.  I didn't know the latest files were on gitHub

Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by WEKarnesky** [comment] 2020-06-02 15:36
No problem, glad it's fixed for you.

**Closed by WEKarnesky** 2020-06-02 15:36 UTC
Labels: bug
