### ISSUE TITLE
Clan I-OS Launchers wrongly weight calculation

### ISSUE THREAD

**Issue by Andai82** [Solaris-Skunk-Werks/solarisskunkwerks#246] opened 2021-06-11 15:13 UTC
Improved One-Shot launchers weigh half a ton less than their standard versions. The minimum weight of an Inner Sphere launcher is half a ton, while the minimum weight of a Clan I-OS launcher is a quarter ton.

The Clan SRM-2 I-OS launchers weights 0,5tons in SSW_0.7.6, which is wrong. Therefore not possible to design a mech like the Crossbow T with 14 SRM2 I-OS launchers

**Comment by WEKarnesky** [comment] 2021-06-11 16:44
Duplicate of #245, and fixed in hotfix.  Hotfix release will be released this weekend.  Until then, you can download the latest CI build with fix implemented here https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/actions/runs/916666520

You can also alter your local copy of `Data/Equipment/weapons.json`.  Just search for `CLSRM2 (iOS)`, then change the lines that is `"Tonnage": 0.5`

**Closed by WEKarnesky** 2021-06-11 16:44 UTC
