### ISSUE TITLE
Include Design Quirks in the Record Sheet Mech Data Table

### ISSUE THREAD

**Issue by JstnB** [Solaris-Skunk-Werks/solarisskunkwerks#211] opened 2020-11-13 17:35 UTC
Since design quirks are not presently shown on record sheets, it would be nice if there were the option to add design quirks in the Mech Data Table, maybe in a new section after the Weapons and Equipment section of that table.

**Comment by WEKarnesky** [comment] 2020-11-13 17:52
This is a Duplicate of Ticket #92 Request: Display for Quirks on Record Sheet and will be closed.  Please add any further detail or suggestions to that ticket.

**Closed by WEKarnesky** 2020-11-13 17:52 UTC
